# Generated by Django 4.2.2 on 2023-06-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_calories_bmi_date_bmi_result_bmi_status_bmi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='user',
        ),
    ]
