# Generated by Django 4.2.2 on 2023-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_bmi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='status',
            field=models.CharField(choices=[('no', 'No physical activity'), ('little', 'Little physical activity (1-3 times a week)'), ('average', 'Average physical activity (3-5 times a week)'), ('high', 'High physical activity (daily physical activity)')], max_length=60),
        ),
    ]
